<script setup lang="ts">
import { computed, ref } from 'vue'
import Sparkline from '../components/Sparkline.vue'
import DIcon from '../components/DIcon.vue'
import { useSimulationStore } from '../stores/simulation'

const store = useSimulationStore()
const range = ref('15分钟')
const selected = ref('temp-03')
const ranges = ['1分钟','5分钟','15分钟','1小时','6小时','24小时']
const tempPoints = computed(() => store.samples.map((v,i) => `${(i/(store.samples.length-1))*100},${70-(v-40)*2}`).join(' '))
const ampPoints = computed(() => store.samples.map((v,i) => `${(i/(store.samples.length-1))*100},${73-(8 + Math.sin(v+i)*2)*3}`).join(' '))
const devices = computed(() => store.devices.filter(d => d.id !== 'gateway-01'))
const pointRows = computed(() => [
  { icon: 'temperature', name: '设备3-温度', value: store.temperature.toFixed(1), unit: '°C', state: '告警' },
  { icon: 'activity', name: '电机2-电流', value: '10.2', unit: 'A', state: '正常' },
  { icon: 'meter', name: '电表1-电压', value: '220.1', unit: 'V', state: '正常' },
  { icon: 'gauge', name: '环境-湿度', value: '45.3', unit: '%RH', state: '正常' },
])
</script>

<template>
  <div class="monitor page">
    <section class="monitor-head">
      <div class="container head-inner">
        <div><div class="title-row"><h1>设备监控演示</h1><span class="demo-badge"><i class="dot"></i>模拟数据 · 自动刷新</span></div><p>基于统一的设备与点位模型，演示多协议接入、实时数据监控与告警管理能力。</p></div>
        <div class="profile-switch"><button class="active"><DIcon name="gateway" :size="17" />T153MX<DIcon name="chevronDown" :size="15" /></button><button>Lite</button></div>
        <div class="safe-note"><DIcon name="info" :size="14" />仅演示，不控制真实设备</div>
        <div class="head-slogan">连接工业现场<br>让数据创造价值</div>
      </div>
    </section>
    <div class="monitor-body">
      <aside class="side-nav"><button class="active"><DIcon name="monitor" :size="19" />运行总览</button><button><DIcon name="table" :size="19" />设备与点位</button><button><DIcon name="network" :size="19" />网络通信</button><button><DIcon name="alarm" :size="19" />告警记录</button><span>开放连接<br>驱动工业智能<br>—</span></aside>
      <main class="monitor-main">
        <section class="metrics">
          <div class="metric-card surface"><span class="metric-icon"><DIcon name="monitor" :size="24" /></span><div><span class="metric-label">在线设备</span><div class="metric-value">{{ store.onlineCount + 4 }} / 9 <small>⌃ +1</small></div></div><Sparkline :values="store.samples" /></div>
          <div class="metric-card surface"><span class="metric-icon"><DIcon name="database" :size="24" /></span><div><span class="metric-label">采集点位</span><div class="metric-value">32 <small>⌃ +4</small></div></div><Sparkline :values="store.samples.map(v => v*.8)" /></div>
          <div class="metric-card surface warning"><span class="metric-icon"><DIcon name="alarm" :size="24" /></span><div><span class="metric-label">活跃告警</span><div class="metric-value">{{ store.activeAlarms }} <small>⌃ +1</small></div></div><Sparkline color="#e89219" :values="store.samples.map((v,i)=>v + (i%7===0?5:0))" /></div>
          <div class="metric-card surface"><span class="metric-icon"><DIcon name="cpu" :size="24" /></span><div><span class="metric-label">CPU 使用率</span><div class="metric-value">24%</div></div><Sparkline color="#0cae8d" :values="store.samples.map((v,i)=>20 + Math.sin(v+i)*5)" /></div>
        </section>
        <section class="monitor-grid">
          <div class="left-column">
            <div class="trend surface">
              <header><h2>关键点位趋势</h2><div class="ranges"><button v-for="item in ranges" :key="item" :class="{ active: range === item }" @click="range = item">{{ item }}</button></div></header>
              <div class="chart-legend"><span class="temp"><i></i>温度 (°C)</span><span class="amp"><i></i>电流 (A)</span></div>
              <div class="main-chart">
                <div class="y-axis"><span>80</span><span>60</span><span>40</span><span>20</span><span>0</span></div>
                <svg viewBox="0 0 100 78" preserveAspectRatio="none"><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2676f3" stop-opacity=".18"/><stop offset="1" stop-color="#2676f3" stop-opacity="0"/></linearGradient></defs><polygon :points="`0,78 ${tempPoints} 100,78`" fill="url(#trend-fill)"/><polyline :points="tempPoints" fill="none" stroke="#2676f3" stroke-width="1.2" vector-effect="non-scaling-stroke"/><polyline :points="ampPoints" fill="none" stroke="#ed8a0a" stroke-width="1.2" vector-effect="non-scaling-stroke"/></svg>
                <div class="cursor"></div><div class="tooltip"><small>演示时钟</small><b><i class="temp"></i>温度　{{ store.temperature.toFixed(1) }} °C</b><b><i class="amp"></i>电流　12.3 A</b></div>
                <div class="x-axis"><span>14:20</span><span>14:25</span><span>14:30</span><span>14:35</span><span>14:40</span><span>14:45</span></div>
              </div>
            </div>
            <div class="point-list surface"><h2>点位列表</h2><div class="point-table"><b>点位</b><b>当前值</b><b>单位</b><b>状态</b><b>更新时间</b><template v-for="row in pointRows" :key="row.name"><span><DIcon :name="row.icon" :size="15" />{{ row.name }}</span><span>{{ row.value }}</span><span>{{ row.unit }}</span><span :class="row.state === '告警' ? 'alarm' : 'normal'"><i class="dot"></i>{{ row.state }}</span><span>演示时钟 · 刚刚</span></template></div></div>
          </div>
          <div class="right-column">
            <div class="field-devices surface"><header><h2>现场设备</h2><div><span class="normal">● 在线 {{ store.onlineCount + 3 }}</span><span class="alarm">● 告警 {{ store.activeAlarms }}</span><span class="offline">● 离线 1</span></div></header><button v-for="device in devices" :key="device.id" :class="{ selected: selected === device.id, warning: device.state === 'warning' }" @click="selected = device.id; store.select(device.id)"><span class="device-icon"><DIcon :name="device.kind === 'meter' ? 'meter' : device.kind === 'motor' ? 'activity' : 'temperature'" :size="24" /></span><span><b>{{ device.name }}</b><small>{{ device.protocol }}　{{ device.channel }}</small></span><em :class="device.state">● {{ device.state === 'warning' ? '告警' : device.state === 'offline' ? '离线' : '在线' }}</em><span class="device-value">{{ device.kind === 'temperature' ? '温度' : device.kind === 'motor' ? '转速' : '电压' }}　<b>{{ device.value }} {{ device.unit }}</b><small>{{ device.kind === 'temperature' ? '状态　运行中' : device.kind === 'motor' ? '电流　10.2 A' : '电流　8.4 A' }}</small></span><DIcon name="chevronRight" :size="18" /></button></div>
            <div class="alarm-card surface"><header><h2><DIcon name="alarm" :size="18" />温度阈值提醒 <small>未确认</small></h2><button>查看记录<DIcon name="chevronRight" :size="15" /></button></header><div class="alarm-value">{{ store.temperature.toFixed(1) }} °C <span>&gt; 50 °C</span></div><p>设备3-温度 当前值 {{ store.temperature.toFixed(1) }} °C，已超过阈值 50 °C</p><dl><dt><DIcon name="clock" :size="14" />发生时间</dt><dd>演示时钟 · 刚刚</dd><dt><DIcon name="home" :size="14" />所属设备</dt><dd>温度 - 03</dd><dt><DIcon name="alarm" :size="14" />点位信息</dt><dd>设备3-温度 (SOEM EtherCAT)</dd></dl></div>
          </div>
        </section>
      </main>
    </div>
    <footer class="page-footer"><span>DshanControl　让工业连接更简单</span><span>UI 概念设计 · 演示数据</span></footer>
  </div>
</template>

<style scoped>
.monitor { min-height: 872px; background: #f4f8fd; }.monitor-head { height: 125px; background: linear-gradient(110deg,#f8fbff 0,#eef7ff 66%,#dceaf7 100%); border-bottom: 1px solid #dde7f2; }.head-inner { position: relative; height: 100%; display: flex; align-items: flex-start; padding-top: 38px; }.title-row { display: flex; align-items: center; gap: 22px; }.title-row h1 { margin: 0; color: #0c284f; font-size: 25px; }.title-row .demo-badge { min-height: 30px; color: #1563c0; border-color: #b9d8fb; background: #eaf4ff; }.head-inner > div:first-child > p { margin: 7px 0 0; color: #68809d; font-size: 13px; }.profile-switch { margin: 5px 0 0 55px; display: flex; height: 47px; border: 1px solid #d9e4ef; border-radius: 8px; background: rgba(255,255,255,.55); }.profile-switch button { min-width: 83px; border: 0; border-left: 1px solid #dce6f0; background: transparent; color: #6b809b; }.profile-switch button.active { min-width: 175px; display:flex; align-items:center; justify-content:center; gap:10px; color: #17385e; font-weight: 700; border: 0; }.safe-note { margin: 18px 0 0 45px; display:flex; align-items:center; gap:6px; color: #7489a4; font-size: 12px; }.head-slogan { margin-left: auto; padding-left: 22px; border-left: 2px solid var(--primary); color: #627b99; line-height: 1.55; }
.monitor-body { height: 706px; display: grid; grid-template-columns: 190px 1fr; }.side-nav { position: relative; padding: 14px 12px; background: linear-gradient(180deg,#f9fcff,#edf6ff); }.side-nav button { width: 100%; height: 52px; padding-left: 20px; display: flex; align-items:center; gap:13px; border: 0; border-radius: 8px; background: transparent; color: #375677; text-align: left; font-size: 14px; }.side-nav button.active { color: var(--primary); background: #e7f1ff; border-left: 3px solid var(--primary); font-weight: 700; }.side-nav > span { position: absolute; left: 38px; bottom: 30px; color: #8aa1bd; line-height: 1.75; font-size: 13px; }
.monitor-main { min-width: 0; padding: 13px 15px; }.metrics { height: 96px; display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; }.metric-value small { color: var(--success); font-size: 11px; }.metric-card.warning .metric-icon { color: var(--warning); background: #fff8ec; }.metric-card.warning .metric-value { color: #a81410; }.metric-card.warning .metric-value small { color: var(--warning); }
.monitor-grid { height: 582px; margin-top: 12px; display: grid; grid-template-columns: minmax(620px,1.58fr) minmax(420px,1fr); gap: 12px; }.left-column, .right-column { min-width: 0; display: grid; gap: 12px; }.left-column { grid-template-rows: 320px 1fr; }.right-column { grid-template-rows: 320px 1fr; }
.trend { padding: 0 20px; }.trend header, .field-devices header { height: 58px; display: flex; align-items: center; justify-content: space-between; }.trend h2, .field-devices h2, .point-list h2, .alarm-card h2 { margin: 0; color: #173659; font-size: 16px; }.ranges { display: flex; border: 1px solid #d9e4ef; border-radius: 6px; overflow: hidden; }.ranges button { height: 32px; padding: 0 15px; border: 0; border-right: 1px solid #dce5ef; background: #f8fafc; color: #55708f; font-size: 11px; }.ranges button.active { color: #fff; background: var(--primary); }.chart-legend { display: flex; gap: 30px; color: #55708f; font-size: 11px; }.chart-legend span, .tooltip b { display: flex; align-items: center; gap: 6px; }.chart-legend i, .tooltip i { width: 8px; height: 8px; border-radius: 50%; background: var(--primary); }.chart-legend .amp i, .tooltip i.amp { background: #ed8a0a; }.main-chart { position: relative; height: 210px; margin-top: 4px; margin-left: 28px; background: repeating-linear-gradient(to bottom,transparent,transparent 36px,#e7edf4 37px); }.main-chart svg { position: absolute; inset: 5px 10px 23px 20px; width: calc(100% - 30px); height: calc(100% - 28px); }.y-axis { position: absolute; left: -28px; top: 0; bottom: 20px; display: flex; flex-direction: column; justify-content: space-between; color: #7b8fa8; font-size: 9px; }.x-axis { position: absolute; left: 0; right: 0; bottom: 0; display: flex; justify-content: space-between; color: #7890aa; font-size: 9px; }.cursor { position: absolute; left: 45%; top: 6px; bottom: 21px; border-left: 1px dashed #607d9d; }.tooltip { position: absolute; left: 48%; top: 4px; width: 150px; padding: 10px 12px; border: 1px solid #d8e3ee; border-radius: 7px; background: rgba(255,255,255,.95); box-shadow: 0 8px 18px rgba(35,70,111,.11); color: #244565; font-size: 11px; }.tooltip small { display: block; margin-bottom: 6px; color: #6f839d; }.tooltip b { margin-top: 4px; }
.point-list { padding: 14px 14px; }.point-list h2 { margin: 0 0 8px; }.point-table { display: grid; grid-template-columns: 1.4fr .8fr .7fr .85fr 1.4fr; }.point-table b, .point-table span { height: 31px; padding: 0 14px; display: flex; align-items: center; gap:7px; border-bottom: 1px solid #e8eef5; font-size: 11px; }.point-table b { color: #657a94; background: #f4f7fa; }.point-table span { color: #294866; }.point-table span:nth-child(n+6):nth-child(-n+10) { background: #fff7e8; }.point-table .dot { display: inline-block; margin-right: 6px; }.point-table .normal { color: #316259; }.point-table .alarm { color: #b76b07; }
.field-devices { padding: 0 12px; }.field-devices header { height: 58px; padding: 0 6px; border-bottom: 1px solid #e6edf5; }.field-devices header div { display: flex; gap: 18px; font-size: 10px; }.normal { color: var(--success); }.alarm { color: var(--warning); }.offline { color: var(--offline); }.field-devices > button { width: 100%; height: 81px; padding: 9px 12px; display: grid; grid-template-columns: 54px 1fr 82px 128px 12px; align-items: center; gap: 10px; border: 0; border-bottom: 1px solid #e6edf5; background: #fff; text-align: left; cursor: pointer; }.field-devices > button.selected { border: 2px solid var(--primary); border-radius: 7px; background: #fff9ec; }.device-icon { width: 45px; height: 50px; display: grid; place-items: center; border-radius: 8px; background: #eef3f8; color: #607b96; font-size: 25px; }.field-devices button span b, .field-devices button span small { display: block; }.field-devices button span b { color: #163558; font-size: 13px; }.field-devices button span small { margin-top: 5px; color: #6c829e; font-size: 10px; }.field-devices button em { font-style: normal; font-size: 11px; }.field-devices button em.online { color: var(--success); }.field-devices button em.warning { color: var(--warning); }.field-devices button em.offline { color: var(--offline); }.device-value { color: #536f8d; font-size: 10px; }.device-value b { display: inline !important; color: #1c3b5d !important; }.field-devices button strong { color: #93a6bd; font-size: 21px; font-weight: 400; }
.alarm-card { padding: 16px 20px; }.alarm-card header { display: flex; align-items: center; justify-content: space-between; }.alarm-card h2,.alarm-card header button,.alarm-card dt { display:flex; align-items:center; gap:7px; }.alarm-card h2 small { margin-left: 7px; padding: 3px 6px; border: 1px solid #f6d4aa; border-radius: 8px; color: var(--warning); font-size: 9px; }.alarm-card header button { height: 34px; padding: 0 18px; border: 1px solid var(--primary); border-radius: 6px; color: var(--primary); background: #fff; font-size: 11px; }.alarm-value { margin-top: 8px; color: #b31310; font-size: 30px; font-weight: 800; }.alarm-value span { color: #183a5c; font-size: 17px; }.alarm-card > p { margin: 2px 0 10px; color: #6f829c; font-size: 11px; }.alarm-card dl { display: grid; grid-template-columns: 110px 1fr; margin: 0; color: #5c7592; font-size: 11px; line-height: 1.9; }.alarm-card dd { margin: 0; color: #3a5878; }
@media (max-width: 1200px) { .monitor-body { grid-template-columns: 150px 1fr; height: auto; }.metrics { grid-template-columns: 1fr 1fr; height: auto; }.monitor-grid { height: auto; grid-template-columns: 1fr; }.left-column,.right-column { grid-template-rows: auto; }.trend,.field-devices { min-height: 320px; }.profile-switch,.safe-note { display: none; } }
@media (max-width: 760px) { .monitor-head { height: auto; }.head-inner { padding: 24px 0; }.title-row { align-items: flex-start; flex-direction: column; gap: 8px; }.head-slogan { display: none; }.monitor-body { grid-template-columns: 1fr; }.side-nav { display: flex; overflow-x: auto; padding: 7px; }.side-nav button { min-width: 130px; }.side-nav span { display: none; }.monitor-main { padding: 10px; }.metrics { grid-template-columns: 1fr; }.monitor-grid { grid-template-columns: 1fr; }.ranges { overflow-x: auto; max-width: 60%; }.ranges button { min-width: 65px; padding: 0 7px; }.field-devices > button { grid-template-columns: 45px 1fr 65px 12px; }.device-value { display: none; }.point-list { overflow-x: auto; }.point-table { min-width: 650px; }.tooltip { left: 36%; }.page-footer { display: none; } }
@media (max-width: 760px) { .monitor-body { grid-template-columns: minmax(0,1fr); }.side-nav { max-width: 100vw; }.monitor-main,.monitor-grid,.left-column,.right-column,.trend,.point-list { min-width: 0; width: 100%; max-width: 100%; }.monitor-grid,.left-column,.right-column { grid-template-columns: minmax(0,1fr); }.trend { overflow: hidden; }.point-list { overflow-x: auto; }.point-table { width: 650px; min-width: 650px; } }
</style>
